/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getacar;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Erdy
 */
public class OrgFrame extends javax.swing.JFrame {

    /**
     * Creates new form OrgFrame
     */
    public OrgFrame() {
        initComponents();
        jLabelType.setVisible(false);
        jRadioButtonHatchback.setVisible(false);
        jRadioButtonSUV.setVisible(false);
        jRadioButtonSedan.setVisible(false);
        jLabelCylinderNum.setVisible(false);
        jTextFieldCylinderNumber.setVisible(false);
        jLabelCapacity.setVisible(false);
        jTextFieldCapacity.setVisible(false);
        jCheckBoxTV.setVisible(false);
        jCheckBoxInternet.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBoxIsRented = new javax.swing.JCheckBox();
        jTextFieldBrand = new javax.swing.JTextField();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldYear = new javax.swing.JTextField();
        jTextFieldKilometres = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldTopSpeed = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jRadioButtonHatchback = new javax.swing.JRadioButton();
        jRadioButtonSedan = new javax.swing.JRadioButton();
        jRadioButtonSUV = new javax.swing.JRadioButton();
        jLabelCapacity = new javax.swing.JLabel();
        jTextFieldCapacity = new javax.swing.JTextField();
        jCheckBoxTV = new javax.swing.JCheckBox();
        jCheckBoxInternet = new javax.swing.JCheckBox();
        jLabelCylinderNum = new javax.swing.JLabel();
        jTextFieldCylinderNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Organization Panel");
        setSize(new java.awt.Dimension(400, 423));

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Car", "Motorcycle" }));
        jComboBoxType.setSelectedIndex(-1);
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jLabel2.setText("Vehicle Type");

        jLabel1.setText("Vehicle Panel");

        jLabel3.setText("Brand");

        jLabel4.setText("Model");

        jLabel5.setText("Color");

        jLabel6.setText("Top Speed");

        jLabel7.setText("Year");

        jLabel8.setText("Kilometres");

        jLabel9.setText("Price");

        jCheckBoxIsRented.setText("Rented");
        jCheckBoxIsRented.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIsRentedActionPerformed(evt);
            }
        });

        jLabelType.setText("Type");

        buttonGroup1.add(jRadioButtonHatchback);
        jRadioButtonHatchback.setText("Hatchback");

        buttonGroup1.add(jRadioButtonSedan);
        jRadioButtonSedan.setText("Sedan");

        buttonGroup1.add(jRadioButtonSUV);
        jRadioButtonSUV.setText("SUV");

        jLabelCapacity.setText("Capacity");

        jCheckBoxTV.setText("TV");

        jCheckBoxInternet.setText("Internet");

        jLabelCylinderNum.setText("Cylinder Number");

        jButton1.setText("Sell Vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxIsRented)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldKilometres, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButtonSedan))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButtonSUV))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTopSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonHatchback)
                                    .addComponent(jLabelType))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxInternet)
                                    .addComponent(jCheckBoxTV)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCapacity)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCapacity))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCylinderNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCylinderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldKilometres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTopSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxIsRented)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jLabelCylinderNum)
                    .addComponent(jTextFieldCylinderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonHatchback)
                    .addComponent(jLabelCapacity)
                    .addComponent(jTextFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSedan)
                    .addComponent(jCheckBoxTV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSUV)
                    .addComponent(jCheckBoxInternet))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxIsRentedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIsRentedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxIsRentedActionPerformed

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        // TODO add your handling code here:
        if (jComboBoxType.getSelectedItem().equals("Bus"))
        {
            jLabelType.setVisible(false);
            jRadioButtonHatchback.setVisible(false);
            jRadioButtonSUV.setVisible(false);
            jRadioButtonSedan.setVisible(false);
            jLabelCylinderNum.setVisible(false);
            jTextFieldCylinderNumber.setVisible(false);
            jLabelCapacity.setVisible(true);
            jTextFieldCapacity.setVisible(true);
            jCheckBoxTV.setVisible(true);
            jCheckBoxInternet.setVisible(true);
        }
        else if(jComboBoxType.getSelectedItem().equals("Car"))
        {
            jLabelType.setVisible(true);
            jRadioButtonHatchback.setVisible(true);
            jRadioButtonSUV.setVisible(true);
            jRadioButtonSedan.setVisible(true);
            jLabelCylinderNum.setVisible(false);
            jTextFieldCylinderNumber.setVisible(false);
            jLabelCapacity.setVisible(false);
            jTextFieldCapacity.setVisible(false);
            jCheckBoxTV.setVisible(false);
            jCheckBoxInternet.setVisible(false);
        }
        else
        {
            jLabelType.setVisible(false);
            jRadioButtonHatchback.setVisible(false);
            jRadioButtonSUV.setVisible(false);
            jRadioButtonSedan.setVisible(false);
            jLabelCylinderNum.setVisible(true);
            jTextFieldCylinderNumber.setVisible(true);
            jLabelCapacity.setVisible(false);
            jTextFieldCapacity.setVisible(false);
            jCheckBoxTV.setVisible(false);
            jCheckBoxInternet.setVisible(false); 
        }
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String brand = jTextFieldBrand.getText();
        String model = jTextFieldModel.getText();
        String color = jTextFieldColor.getText();
        int year = Integer.parseInt(jTextFieldYear.getText());
        int kilometres = Integer.parseInt(jTextFieldKilometres.getText());
        int price = Integer.parseInt(jTextFieldPrice.getText());
        int topspeed = Integer.parseInt(jTextFieldTopSpeed.getText());
        boolean isRented = jCheckBoxIsRented.isSelected();
        if (jComboBoxType.getSelectedItem().equals("Bus"))
        {
            int capacity = Integer.parseInt(jTextFieldCapacity.getText());
            boolean tv = jCheckBoxTV.isSelected();
            boolean internet = jCheckBoxInternet.isSelected();
            Bus b = new Bus(brand, model, color, topspeed, year, kilometres, price, isRented, capacity, internet, tv);
            VehicleSys.addVehicle(b);
            b.sell(b);
        }
        else if (jComboBoxType.getSelectedItem().equals("Car"))
        {
            String type;
            if (jRadioButtonHatchback.isSelected())
                type = "Hatchback";
            else if(jRadioButtonSUV.isSelected())
                type = "SUV";
            else
                type = "Sedan";
            Car c = new Car(brand, model, color, topspeed, year, kilometres, price, isRented, type);
            VehicleSys.addVehicle(c);
            c.sell(c);
        }
        else if (jComboBoxType.getSelectedItem().equals("Motorcycle"))
        {
            int cylinderNum = Integer.parseInt(jTextFieldCylinderNumber.getText());
            Motorcycle m = new Motorcycle (brand, model, color, topspeed, year, kilometres, price, isRented, cylinderNum);
            VehicleSys.addVehicle(m);
            m.sell(m);      
        }
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxInternet;
    private javax.swing.JCheckBox jCheckBoxIsRented;
    private javax.swing.JCheckBox jCheckBoxTV;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCapacity;
    private javax.swing.JLabel jLabelCylinderNum;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JRadioButton jRadioButtonHatchback;
    private javax.swing.JRadioButton jRadioButtonSUV;
    private javax.swing.JRadioButton jRadioButtonSedan;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldCapacity;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldCylinderNumber;
    private javax.swing.JTextField jTextFieldKilometres;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldTopSpeed;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
}
